Day 1 — NumPy for Structural Analysis

Stress calculation using Force/Area
Failure detection using threshold conditions
Multi-dimensional analysis using NumPy
Beam comparison and data normalization
20 random forces (1000–5000)
20 random areas (5–25)

**project**-1 italicized text Basic Stress*

In [ ]:
import numpy as np
forces=np.random.randint(1000,5000,20)
areas=np.random.randint(5,25,20)
stress = forces/areas
A=np.max(stress)
B=np.mean(stress)
print("compute stress:\n",stress)
print("max stress:\n",A)
print("mean of stress:\n",B)

compute stress:
 [626.42857143 174.73684211 818.16666667  67.5        121.27777778
 199.69230769 228.85714286 554.625      277.57142857 209.2
 506.4        180.38888889 189.4375     154.66666667 179.64705882
 550.33333333 349.2        226.77272727 117.33333333  70.75      ]
max stress:
 818.1666666666666
mean of stress:
 290.1492622708818


**project-2** Failure Detection
Find all values where stress > 120
Print their indices
Count how many failure points exist

In [ ]:
import numpy as np
forces=np.random.randint(1000,5000,20)
areas=np.random.randint(5,25,20)
stress= forces/areas
failure_values=stress[stress>110]
indices_points=np.where(stress>110)
print("failure_values:\n",failure_values)
print("indices points:\n",indices_points)

failure_values:
 [181.5        195.89473684 252.18181818 576.6        543.71428571
 356.42857143 164.34782609 350.16666667 173.625      476.5
 235.94117647 203.35714286 218.         161.85714286 199.73913043
 322.25       152.375      321.06666667 360.44444444]
indices points:
 (array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 13, 14, 15, 16, 17,
       18, 19]),)


project-3 Random Engineering Dataset
Generate:
20 random forces (1000–5000)
20 random areas (5–25)
Compute stress
Find min, max, mean
Sort stress values

In [ ]:
import numpy as np
forces=np.random.randint(1000,5000,20)
areas=np.random.randint(5,25,20)
stress=forces/areas
A=np.max(stress)
B=np.min(stress)
C=np.mean(stress)
D=np.sort(stress)
print("max of stress:\n",A)
print("min of stress:\n",B)
print("mean of stress:\n",C)
print("sort of stress:\n",D)

max of stress:
 602.125
min of stress:
 49.541666666666664
mean of stress:
 229.93436328506377
sort of stress:
 [ 49.54166667  70.          86.375      116.3        136.53846154
 148.68421053 160.         165.90909091 167.5        188.42857143
 201.27777778 206.75       218.05882353 251.05263158 264.33333333
 274.88888889 347.66666667 452.85714286 490.4        602.125     ]


**PROBLEM 4** — 2D Structural Data
Reshape your stress into a 4×5 matrix
Print matrix
Find mean along:
axis=0
axis=1

In [ ]:
import numpy as np
forces=np.random.randint(1000,5000,20)
areas=np.random.randint(5,25,20)
stress=forces/areas
A=stress.reshape(4,5)
print("reshape into 2D:\n",A)
B=np.mean(A,axis=0)
print("mean of stress along axis=0:\n",B)
C=np.mean(A,axis=1)
print("mean of stress along axis=1:\n",C)

reshape into 2D:
 [[256.75       153.05       321.72727273 126.         163.94736842]
 [189.28571429 485.5        155.35       174.33333333 134.36363636]
 [166.85       297.41666667 766.4        160.76190476 135.05      ]
 [389.66666667 189.11764706 162.13333333 444.6        162.        ]]
mean of stress along axis=0:
 [250.63809524 281.27107843 351.40265152 226.42380952 148.8402512 ]
mean of stress along axis=1:
 [204.29492823 227.7665368  305.29571429 269.50352941]


**PROBLEM 5 **— Beam Comparison (IMPORTANT)
Create 2 beams:
Beam A stress values
Beam B stress values
Stack them into 2D array
Compare which beam has higher average stress
Find difference between beams

In [ ]:
import numpy as np
beamA=np.array([[1,2],[3,4]])
beamB=np.array([[5,6],[7,8]])
C=np.stack((beamA.flatten(),beamB.flatten()))
print("stack them into 2d array:\n",C)
D=np.mean(beamA)
print(" mean of beamA:\n",D)
F=np.mean(beamB)
print(" mean of beamB:\n",F)
if D>F:
    print("beamA isis more critical")
else:
    print("beamB is is more critical")
E=np.subtract(beamA,beamB)
print("difference btw beams:\n ",E)

stack them into 2d array:
 [[1 2 3 4]
 [5 6 7 8]]
 mean of beamA:
 2.5
 mean of beamB:
 6.5
beamB is is more critical
difference btw beams:
  [[-4 -4]
 [-4 -4]]


**PROBLEM 6** — Advanced (Standout Level)
Reshape (4×5)
Mean along axis=0
Mean along axis=1
Max per row

In [ ]:
import numpy as np
forces=np.random.randint(1000,5000,20)
areas=np.random.randint(5,25,20)
stress = forces/areas
C=stress.reshape(4,5)
print("reshape(4,5):\n",C)
S=C[C>250]
print("failure in stress:\n",S)
P=np.where(C>250)
print("indices o failure:\n",P)

reshape(4,5):
 [[206.69565217 146.14285714 539.4        200.07692308 141.875     ]
 [305.375      192.55        63.84210526 304.1875     198.9       ]
 [511.4        177.09090909 100.31578947 132.125       98.61111111]
 [ 54.69565217 244.05       102.          48.95454545 313.71428571]]
failure in stress:
 [539.4        305.375      304.1875     511.4        313.71428571]
indices o failure:
 (array([0, 1, 1, 2, 3]), array([2, 0, 3, 0, 4]))
